language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-webapp-block' ]; then cd .. && eval "mv $currentfolder generator-webapp-block" && cd generator-webapp-block; fi

